---
- name: Installing utils
  yum:
    name: "{{ web.packages }}"
    state: present

- name: Startup Nginx
  systemd:
    name: "nginx"
    state: started
    enabled: yes
    daemon_reload: yes
...
