---
- name: Installing utils
  yum:
    name: "{{ web.packages }}"
    state: present

#- name: Startup Nginx
#  systemd:
#    name: "nginx"
#    state: started
#    enabled: yes
#    daemon_reload: yes


- name: FirewallD add ports
  ansible.posix.firewalld:
    zone: "{{ web.firewalld.zone }}"
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{ web.firewalld.ports }}"
...