---
- name: Installing utils
  yum:
    name: "{{ web.packages }}"
    state: present

#- name: Startup Nginx
#  systemd:
#    name: "nginx"
#    state: started
#    enabled: yes
#    daemon_reload: yes

- name: FirewallD add ports
  firewalld:
    zone: "{{ web.firewalld.zone }}"
    port: "{{ web.firewalld.ports }}"
    permanent: yes
    state: enabled
    immediate: yes
...
