---

- name: PRE_CONFIGURE
  hosts: all
  become: yes
  gather_facts: true
  roles:
    - common

- name: Installing/Configuring NGINX
  hosts: Nginx
  become: yes
  gather_facts: true
  roles:
    - nginx-configure

...